# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: moto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='moto.proto',
  package='protoItems',
  syntax='proto3',
  serialized_options=b'Z\007./proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nmoto.proto\x12\nprotoItems\"\"\n\rItemSignature\x12\x11\n\tSignature\x18\x01 \x03(\x04\"\x18\n\x08ItemText\x12\x0c\n\x04Text\x18\x01 \x01(\t2N\n\x0bItemService\x12?\n\x0cGetSignature\x12\x14.protoItems.ItemText\x1a\x19.protoItems.ItemSignatureB\tZ\x07./protob\x06proto3'
)




_ITEMSIGNATURE = _descriptor.Descriptor(
  name='ItemSignature',
  full_name='protoItems.ItemSignature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Signature', full_name='protoItems.ItemSignature.Signature', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=60,
)


_ITEMTEXT = _descriptor.Descriptor(
  name='ItemText',
  full_name='protoItems.ItemText',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Text', full_name='protoItems.ItemText.Text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['ItemSignature'] = _ITEMSIGNATURE
DESCRIPTOR.message_types_by_name['ItemText'] = _ITEMTEXT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ItemSignature = _reflection.GeneratedProtocolMessageType('ItemSignature', (_message.Message,), {
  'DESCRIPTOR' : _ITEMSIGNATURE,
  '__module__' : 'moto_pb2'
  # @@protoc_insertion_point(class_scope:protoItems.ItemSignature)
  })
_sym_db.RegisterMessage(ItemSignature)

ItemText = _reflection.GeneratedProtocolMessageType('ItemText', (_message.Message,), {
  'DESCRIPTOR' : _ITEMTEXT,
  '__module__' : 'moto_pb2'
  # @@protoc_insertion_point(class_scope:protoItems.ItemText)
  })
_sym_db.RegisterMessage(ItemText)


DESCRIPTOR._options = None

_ITEMSERVICE = _descriptor.ServiceDescriptor(
  name='ItemService',
  full_name='protoItems.ItemService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=88,
  serialized_end=166,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSignature',
    full_name='protoItems.ItemService.GetSignature',
    index=0,
    containing_service=None,
    input_type=_ITEMTEXT,
    output_type=_ITEMSIGNATURE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ITEMSERVICE)

DESCRIPTOR.services_by_name['ItemService'] = _ITEMSERVICE

# @@protoc_insertion_point(module_scope)
