# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import moto_pb2 as moto__pb2


class ItemServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSignature = channel.unary_unary(
                '/protoItems.ItemService/GetSignature',
                request_serializer=moto__pb2.ItemText.SerializeToString,
                response_deserializer=moto__pb2.ItemSignature.FromString,
                )


class ItemServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSignature(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ItemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSignature': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSignature,
                    request_deserializer=moto__pb2.ItemText.FromString,
                    response_serializer=moto__pb2.ItemSignature.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protoItems.ItemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ItemService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSignature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protoItems.ItemService/GetSignature',
            moto__pb2.ItemText.SerializeToString,
            moto__pb2.ItemSignature.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
